package com.example.dvely.change.infrastructure.persistence.entity;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.dvely.change.domain.value.ChangeStatus;
import org.junit.jupiter.api.Test;

/**
 * Track Z (#56) — the change generated by a CODE step now has three additional terminal-ish
 * transitions (MERGED/REJECTED via a RESULT decision) layered on top of the pre-existing
 * PREVIEW_READY -> DEPLOYED webhook transition (design §3.2). These are entity-level unit tests
 * (no Spring context) because the guard being tested lives entirely inside {@link ChangeEntity}.
 */
class ChangeEntityTest {

    @Test
    void markMergedSetsStatusApprovalAndMergeFields() {
        ChangeEntity change = new ChangeEntity(1L, 11L, 21L, "task-1", "preview-1", "요약", "diff");

        change.markMerged(9L, 42, "sha-abc123");

        assertThat(change.getStatus()).isEqualTo(ChangeStatus.MERGED.name());
        assertThat(change.getApprovalId()).isEqualTo(9L);
        assertThat(change.getPrNumber()).isEqualTo(42);
        assertThat(change.getMergeCommitSha()).isEqualTo("sha-abc123");
        assertThat(change.getMergedAt()).isNotNull();
    }

    @Test
    void markMergedAllowsNullPrNumberForTheIdempotentNoOpPath() {
        ChangeEntity change = new ChangeEntity(1L, 11L, 21L, "task-1", "preview-1", "요약", "diff");

        change.markMerged(9L, null, "sha-existing-head");

        assertThat(change.getStatus()).isEqualTo(ChangeStatus.MERGED.name());
        assertThat(change.getPrNumber()).isNull();
        assertThat(change.getMergeCommitSha()).isEqualTo("sha-existing-head");
    }

    @Test
    void markRejectedSetsStatusAndApprovalIdWithoutTouchingMergeFields() {
        ChangeEntity change = new ChangeEntity(1L, 11L, 21L, "task-1", "preview-1", "요약", "diff");

        change.markRejected(9L);

        assertThat(change.getStatus()).isEqualTo(ChangeStatus.REJECTED.name());
        assertThat(change.getApprovalId()).isEqualTo(9L);
        assertThat(change.getPrNumber()).isNull();
        assertThat(change.getMergeCommitSha()).isNull();
        assertThat(change.getMergedAt()).isNull();
    }

    @Test
    void markDeployedTransitionsFromPreviewReady() {
        ChangeEntity change = new ChangeEntity(1L, 11L, 21L, "task-1", "preview-1", "요약", "diff");

        change.markDeployed();

        assertThat(change.getStatus()).isEqualTo(ChangeStatus.DEPLOYED.name());
    }

    @Test
    void markDeployedTransitionsFromMerged() {
        ChangeEntity change = new ChangeEntity(1L, 11L, 21L, "task-1", "preview-1", "요약", "diff");
        change.markMerged(9L, 42, "sha-abc123");

        change.markDeployed();

        assertThat(change.getStatus()).isEqualTo(ChangeStatus.DEPLOYED.name());
    }

    @Test
    void markDeployedIsAGuardedNoOpFromRejected() {
        // Design §3.2: a REJECTED change must never be flipped to DEPLOYED by a stray/late
        // deployment-success webhook (WebhookEventHandler keys purely by taskId, with no
        // knowledge of the RESULT decision).
        ChangeEntity change = new ChangeEntity(1L, 11L, 21L, "task-1", "preview-1", "요약", "diff");
        change.markRejected(9L);

        change.markDeployed();

        assertThat(change.getStatus()).isEqualTo(ChangeStatus.REJECTED.name());
    }
}
