spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

cloudflare:
  api-token:
  zone-id:
  managed-domain: qeploy.com
  managed-target:
  api-base-url: https://api.cloudflare.com/client/v4
  ttl: 1
  proxied: true

dvely:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      model: claude-opus-4-5-20251101
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-4o
