spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

cloudflare:
  api-token:
  zone-id:
  managed-domain: qeploy.com
  managed-target:
  api-base-url: https://api.cloudflare.com/client/v4
  ttl: 1
  proxied: true
